  name: prefectagent
  on:
    push:
      branches: [ main ]
  jobs:
    prefectimage:
      runs-on: ubuntu-latest
      name: prefect-agent-job
      env:
        DOCKER_CLI_EXPERIMENTAL: "enabled"
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Docker Login
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            platforms: linux/amd64,linux/arm64
            push: true
            tags: bondartsov/prefectagent:latest
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
        - name: Clear
          if: always()
          run: |
            rm -f ${HOME}/.docker/config.json